fix getPictureFileName bug
htmlacademy-nodejs/buy-and-sell pull request #3
Opened 2020-02-10 10:44 UTC by pavel-klimov

В старом варианте при number 10 генерируется имя item010.jpg
Этот PR это исправляет.

2020-02-18 06:41 UTC, AntonovIgor requested changes

2020-02-18 06:41 UTC, AntonovIgor commented on src/service/cli/generate.js
> +const getPictureFileName = (number) => number < 10 ? `item0${number}.jpg` : `item${number}.jpg`;
Привет. Ты просто поменял условие местами? Я правильно понял?

2020-02-18 07:16 UTC, pavel-klimov commented on src/service/cli/generate.js
> +const getPictureFileName = (number) => number < 10 ? `item0${number}.jpg` : `item${number}.jpg`;
Да я поменял условия местами и поменял условие на противоположное. По другому можно было бы исправить бак - это заменить > на >=
Проблема которую решает этот фикс - это баг в краевых условиях. Сейчас при вводе 10 (а 10 входит интервал значений) функция выдаёт результат: item010.jpg, что не соответствует условию задачи. После исправления результат становится равным: item10.jpg

2020-02-18 07:18 UTC, pavel-klimov commented on src/service/cli/generate.js
> +const getPictureFileName = (number) => number < 10 ? `item0${number}.jpg` : `item${number}.jpg`;
Можно запустить в консоле, в репле или где удобно старую функцию и новую и посмотреть что они возвращают при number = 10

2020-02-18 07:45 UTC, efiand commented on src/service/cli/generate.js
> +const getPictureFileName = (number) => number < 10 ? `item0${number}.jpg` : `item${number}.jpg`;
По идее это универсальная логика
```
// utils.js
const printNumWithLead0 = (number) => (number< 10) ? `0${number}` : number;

// modulename.js
const getPictureFileName = (number) =>  `item${printNumWithLead0(number)}.jpg`;

```

2020-02-18 08:10 UTC, pavel-klimov commented on src/service/cli/generate.js
> +const getPictureFileName = (number) => number < 10 ? `item0${number}.jpg` : `item${number}.jpg`;
Я согласен, что так лучше, это изменение меняет стиль не моего кода и я как ученик не хочу навязывать своё виденье прекрасного, по этому просто исправил баг.
Сейчас отправлю коммит с этим изменением.

2020-03-27 09:25 UTC, AntonovIgor approved these changes
:+1: Спасибо.

2020-03-27 09:25 UTC, merged